import Link from 'next/link'
import HeaderUserMenu from '@/components/HeaderUserMenu'
import Cart from '@/components/Cart'
import './global.css'
import { AuthProvider } from '@/context/auth'
import { getCurrentUser } from '@/actions/auth'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const initAuth = await getCurrentUser()

  return (
    <html lang="en">
      <body>
        <AuthProvider initAuth={initAuth || {}}>
          <header className="site-header">
            <Link href="/">
              <h1>🛍️ WebBench Shopping Mart</h1>
            </Link>
            <HeaderUserMenu />
          </header>
          <main>{children}</main>
          <footer className="site-footer">
            <p>Copyright: Web Bench</p>
          </footer>
          <Cart />
        </AuthProvider>
      </body>
    </html>
  )
}